version: "3.9"
services:
  web:
    build: .
    ports:
      - 80:80

    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

    privileged: true

    container_name: poc